### PR TITLE
avoid duplication

### PR DESCRIPTION
**Pull request by lazaridiscom**
trivial

### CODE REVIEW

**Comment by lazaridiscom** [comment]
I just realized that there is no CI-Tests running. Note that I made the PR via github-UI (untested, as I planned to see the CI-Tests). So, better check before merge.

**Comment by joadr** [comment]
Actually, I've seen this, as I added the genesis block on the event node, but there are many issues on the code that I don't bother to correct because there're too many. Like this "If Hell":
https://github.com/tronprotocol/tron-cli/blob/master/troncli/h_config.py#L165

**Comment by lazaridiscom** [comment]
Yeah, I noticed this via your #40.

You're right, the code needs some overall refactoring.

But I think this hash-repetition must be eliminated first.

**Comment by wxue** [comment]
@lazaridiscom Thanks for your PR. However, such constants should be defined in constants.py.

Overall refactoring is on our schedule.

**Comment by lazaridiscom** [comment]
> such constants should be defined in constants.py.
this is a local const, independent of any globals.

You simply DONT DUPLICATE LIKE THIS. anyone who does not understand than, should leave the code-base.

**Pull request merged**
